# Get php-fpm base image
FROM php:8.1.31-fpm-alpine3.21 

# Install dependencies for gd
RUN apk add --update zlib-dev libpng-dev

# Install php Extensions
RUN docker-php-ext-install mysqli gd

COPY /services/php/php.ini-production /usr/local/etc/php/php.ini

# Set the working dir for php-fpm
WORKDIR /var/www/html
